# Generated by Django 4.2.2 on 2023-06-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGateWeb3Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('EVM', 'EVM')], default='EVM', max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('private_key', models.CharField(max_length=256)),
                ('mnemonic', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gate_web3_account',
            },
        ),
    ]
