# Generated by Django 4.2.2 on 2023-06-27 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_usergateweb3account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergateweb3account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
