# Generated by Django 4.2.2 on 2023-06-25 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_name', models.FloatField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'supported_chain',
            },
        ),
        migrations.CreateModel(
            name='SupportedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.FloatField()),
                ('is_testnet', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.supportedchain')),
            ],
            options={
                'db_table': 'supported_network',
            },
        ),
        migrations.CreateModel(
            name='SupportedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.supportednetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PROCESSING', 'PROCESSING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('EXPIRED', 'EXPIRED')], default='CREATED', max_length=20)),
                ('amount', models.FloatField()),
                ('link_hash', models.CharField(max_length=100, unique=True)),
                ('payment_account_address', models.CharField(max_length=100, unique=True)),
                ('payment_account_address_private_key', models.CharField(max_length=100, unique=True)),
                ('iteration', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.supportedtoken')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
