# Generated by Django 4.2.2 on 2023-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_invoice_iteration_invoice_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedchain',
            name='chain_name',
            field=models.CharField(max_length=100),
        ),
    ]
