# Generated by Django 4.2.2 on 2023-06-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_supportedchain_chain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportedtoken',
            old_name='name',
            new_name='token_name',
        ),
    ]
