# Generated by Django 4.2.2 on 2023-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_name_supportedtoken_token_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='expiry_mins',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transacrion_details',
            field=models.TextField(default=None, null=True),
        ),
    ]
