# Generated by Django 4.2.2 on 2023-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_invoice_amount_paid_invoice_expiry_mins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
    ]
