# Generated by Django 4.2.2 on 2023-06-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_invoice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PROCESSING', 'PROCESSING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('IGNORED', 'IGNORED')], default='CREATED', max_length=20)),
                ('amount_to_pay', models.FloatField(default=None, null=True)),
                ('amount_paid', models.FloatField(default=None, null=True)),
                ('fee_amount', models.FloatField(default=None, null=True)),
                ('fee_perc', models.FloatField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transacrion_details', models.TextField(default=None, null=True)),
                ('message', models.TextField(default=None, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
            options={
                'db_table': 'refund_transaction',
            },
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PROCESSING', 'PROCESSING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], default='CREATED', max_length=20)),
                ('amount_to_pay', models.FloatField(default=None, null=True)),
                ('amount_paid', models.FloatField(default=None, null=True)),
                ('fee_amount', models.FloatField(default=None, null=True)),
                ('fee_perc', models.FloatField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transacrion_details', models.TextField(default=None, null=True)),
                ('message', models.TextField(default=None, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
            options={
                'db_table': 'payout_transaction',
            },
        ),
    ]
