# Generated by Django 4.2.2 on 2023-06-27 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0008_supportednetwork_url_alter_invoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('GAS', 'GAS'), ('ERC20', 'ERC20'), ('CLOSE_WALLET', 'CLOSE_WALLET')], max_length=20)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('transaction_hash', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('transacrion_details', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.supportednetwork')),
                ('payout_transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payouttransaction')),
                ('refund_transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.refundtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_transaction',
            },
        ),
    ]
