# Generated by Django 4.2.2 on 2023-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_blockchaintransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_address',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='link_hash',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_account_address',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_account_address_private_key',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='supportedchain',
            name='chain_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='supportednetwork',
            name='network_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='supportedtoken',
            name='contract_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='supportedtoken',
            name='symbol',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='supportedtoken',
            name='token_name',
            field=models.CharField(max_length=250),
        ),
    ]
