# Generated by Django 4.2.2 on 2023-07-06 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHookSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_key', models.TextField()),
                ('endpoint', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhook_secret',
            },
        ),
        migrations.CreateModel(
            name='WebHookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INVOICE_SUCCESSFUL', 'INVOICE_SUCCESSFUL'), ('INVOICE_FAILED', 'INVOICE_FAILED'), ('INVOICE_UNDER_REVIEW', 'INVOICE_UNDER_REVIEW'), ('INVOICE_EXPIRED', 'INVOICE_EXPIRED')], max_length=30)),
                ('request_type', models.CharField(choices=[('POST', 'POST')], max_length=30)),
                ('request_data', models.JSONField()),
                ('response_status_code', models.IntegerField(default=0)),
                ('request_sent_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_management.webhooksecret')),
            ],
            options={
                'db_table': 'webhook_request',
            },
        ),
    ]
