# Generated by Django 4.2.2 on 2023-07-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_management', '0002_webhookrequest_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookrequest',
            name='request_data',
            field=models.JSONField(default=dict),
        ),
    ]
