# Generated by Django 4.2.2 on 2023-07-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_management', '0003_alter_webhookrequest_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookrequest',
            name='event_type',
            field=models.CharField(choices=[('INVOICE_SUCCESSFUL', 'INVOICE_SUCCESSFUL'), ('INVOICE_FAILED', 'INVOICE_FAILED'), ('INVOICE_UNDER_REVIEW', 'INVOICE_UNDER_REVIEW'), ('INVOICE_EXPIRED', 'INVOICE_EXPIRED'), ('PAYOUT_SUCCESSFUL', 'PAYOUT_SUCCESSFUL'), ('PAYOUT_FAILED', 'PAYOUT_FAILED'), ('REFUND_SUCCESSFUL', 'REFUND_SUCCESSFUL'), ('REFUND_FAILED', 'REFUND_FAILED')], max_length=30),
        ),
    ]
